#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""为 XLeRobot 生成稳定 USB 设备别名的 udev 规则。

用途：
  把会漂移的 /dev/ttyACM0、/dev/video2 之类设备，固定成：

    /dev/xlerobot/left_bus
    /dev/xlerobot/right_bus
    /dev/xlerobot/top_camera
    /dev/xlerobot/right_wrist_camera

推荐流程：
  1. 先用 check_xlerobot_ports.py 和 check_cameras.py 确认当前端口角色
  2. 用本脚本生成规则文件
  3. sudo 安装到 /etc/udev/rules.d/
  4. 以后 ACT 脚本只使用 /dev/xlerobot/* 固定别名

示例：
  python act/setup_udev_rules.py \
    --left-bus /dev/ttyACM1 \
    --right-bus /dev/ttyACM0 \
    --top-camera /dev/video4 \
    --right-wrist-camera /dev/video2
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


DEFAULT_OUTPUT = Path("/tmp/99-xlerobot.rules")


@dataclass(frozen=True)
class DeviceAlias:
    role: str
    device: str
    subsystem: str
    symlink: str
    group: str


def _run(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(cmd, text=True, stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(exc.output.strip()) from exc


def _udev_props(device: str) -> dict[str, str]:
    path = Path(device)
    if not path.exists():
        raise FileNotFoundError(f"设备不存在：{device}")

    out = _run(["udevadm", "info", "--query=property", f"--name={device}"])
    props: dict[str, str] = {}
    for line in out.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        props[key] = value
    return props


def _rule_for(alias: DeviceAlias) -> tuple[str, list[str]]:
    props = _udev_props(alias.device)
    id_path = props.get("ID_PATH")
    if not id_path:
        raise RuntimeError(
            f"{alias.device} 没有 ID_PATH，无法按 USB 物理口生成稳定规则。"
            "可以试试换 USB 口后重新运行。"
        )

    notes = [
        f"# {alias.role}: {alias.device}",
        f"# ID_PATH={id_path}",
    ]
    serial = props.get("ID_SERIAL") or props.get("ID_SERIAL_SHORT")
    if serial:
        notes.append(f"# ID_SERIAL={serial}")

    rule_parts = [
        f'SUBSYSTEM=="{alias.subsystem}"',
        f'ENV{{ID_PATH}}=="{id_path}"',
        f'GROUP="{alias.group}"',
        'MODE="0660"',
        'TAG+="uaccess"',
        f'SYMLINK+="xlerobot/{alias.symlink}"',
    ]
    return ", ".join(rule_parts), notes


def _write_rules(aliases: list[DeviceAlias], output: Path) -> str:
    blocks: list[str] = [
        '# XLeRobot stable USB aliases',
        '# Generated by: python act/setup_udev_rules.py',
        '# 安装后重新插拔 USB，或执行 udevadm reload/trigger。',
        '',
    ]

    for alias in aliases:
        rule, notes = _rule_for(alias)
        blocks.extend(notes)
        blocks.append(rule)
        blocks.append("")

    text = "\n".join(blocks)
    output.write_text(text, encoding="utf-8")
    return text


def _print_next_steps(output: Path) -> None:
    print("\n✅ 已生成 udev 规则：")
    print(f"   {output}")
    print("\n安装规则：")
    print(f"   sudo cp {output} /etc/udev/rules.d/99-xlerobot.rules")
    print("   sudo udevadm control --reload-rules")
    print("   sudo udevadm trigger")
    print("\n然后重新插拔四根 USB 线，检查别名：")
    print("   ls -l /dev/xlerobot/")
    print("\n以后固定这样设置：")
    print("   export FOLLOWER_PORT1=/dev/xlerobot/left_bus")
    print("   export FOLLOWER_PORT2=/dev/xlerobot/right_bus")
    print("   export CAM_TOP=/dev/xlerobot/top_camera")
    print("   export CAM_RIGHT_WRIST=/dev/xlerobot/right_wrist_camera")
    print("\n完整测试：")
    print("   python act/teleoperate_self.py")


def main() -> int:
    parser = argparse.ArgumentParser(description="生成 XLeRobot udev 固定别名规则")
    parser.add_argument("--left-bus", required=True, help="bus1 / port1：左臂 + 头部，例如 /dev/ttyACM1")
    parser.add_argument("--right-bus", required=True, help="bus2 / port2：右臂 + 两轮底盘，例如 /dev/ttyACM0")
    parser.add_argument("--top-camera", required=True, help="桌面相机，例如 /dev/video4")
    parser.add_argument("--right-wrist-camera", required=True, help="右腕相机，例如 /dev/video2")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="输出规则文件路径")
    args = parser.parse_args()

    aliases = [
        DeviceAlias("左臂 + 头部总线", args.left_bus, "tty", "left_bus", "dialout"),
        DeviceAlias("右臂 + 两轮底盘总线", args.right_bus, "tty", "right_bus", "dialout"),
        DeviceAlias("桌面相机", args.top_camera, "video4linux", "top_camera", "video"),
        DeviceAlias("右腕相机", args.right_wrist_camera, "video4linux", "right_wrist_camera", "video"),
    ]

    try:
        text = _write_rules(aliases, args.output)
    except Exception as exc:  # noqa: BLE001 - 诊断工具需要给出直接可读的错误
        print(f"❌ 生成 udev 规则失败：{exc}")
        return 1

    print(text)
    _print_next_steps(args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
